### Section A: Data Structures & Control Structures

##### 1) Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [118]:
num=[10,20,30,40,50]

In [119]:
### append
num.append(60)

In [120]:
num

[10, 20, 30, 40, 50, 60]

In [121]:
val=[70,80,90]

In [122]:
### extend
num.extend(val)

In [123]:
num

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [124]:
### insert
num.insert(0,5)

In [125]:
num

[5, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [126]:
### remove
num.remove(80)

In [127]:
num

[5, 10, 20, 30, 40, 50, 60, 70, 90]

In [128]:
### pop
num.pop()

90

In [129]:
num

[5, 10, 20, 30, 40, 50, 60, 70]

In [130]:
### index
num.index(5)

0

In [131]:
num.index(30)

3

In [132]:
### count
num.count(40)

1

In [133]:
### sort
num.sort()
num

[5, 10, 20, 30, 40, 50, 60, 70]

In [134]:
### reverse
num.reverse()
num

[70, 60, 50, 40, 30, 20, 10, 5]

In [135]:
### clear
num.clear()
num

[]

##### 2) Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [138]:
stud_names=("Aswin","Athul","Abhishek")

In [139]:
stud_names[1]="Aatlee"

TypeError: 'tuple' object does not support item assignment

##### 3) Create a set of integers with some duplicate values. Print the set and explain the output.

In [140]:
integer={10,10,20,30,30,50}

In [141]:
print(integer)

{10, 20, 50, 30}


##### 4) Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [166]:
key_dict={'name': 'Aswin','age': 21,'city':'Bengaluru'}

In [167]:
key_dict

{'name': 'Aswin', 'age': 21, 'city': 'Bengaluru'}

In [168]:
### Updating age
key_dict['age']=22

In [169]:
### Creating new key
key_dict['email']='aswin2004@gmail.com'

In [170]:
print(key_dict)

{'name': 'Aswin', 'age': 22, 'city': 'Bengaluru', 'email': 'aswin2004@gmail.com'}


##### 5) Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [173]:
age=int(input("Enter your age:"))
if(age>=18):
    print(f"Person is eligible to vote")
else:
    print(f"Person is not eligible to vote")

Enter your age: 15


Person is not eligible to vote


##### 6) Given a 'marks' variable, print the grade:
##### - 90 and above: 'A'
##### - 75–89: 'B'
##### - 50–74: 'C'
##### - Below 50: 'Fail'


In [176]:
marks=int(input("Enter the marks:"))
if marks>=90:
    print("A")
elif marks>=75 and marks<90:
    print("B")
elif marks>=50 and marks<75:
    print("C")
else:
    print("Fail")

Enter the marks: 89


B


##### 7) Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative

In [182]:
n=int(input("Enter the number:"))
if(n>0):
    if n%2==0:
        print("Positive and Even")
    else:
        print("Positive and Odd")
elif(n<0):
    print("Negative")
else:
    print("Zero")

Enter the number: -9


Negative


### Section B: Numpy

##### 8) Create:
##### - A scalar using np.array(5)
##### - A 1D array with values 1 to 5
##### - A 2D array (2x3) with values from 10 to 60 in steps of 10


In [183]:
import numpy as np

In [197]:
### scalar array
scalar_array=np.array(5)
print(scalar_array)

5


In [196]:
### 1D array
one_dim=np.arange(1,6)
print(one_dim)

[1 2 3 4 5]


In [198]:
### 2D array
two_dim=np.arange(10,61,10).reshape(2,3)
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

##### 9) Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [202]:
rand_arr=np.random.randint(0,101,16).reshape(4,4)
rand_arr

array([[34, 43, 57, 10],
       [27, 55, 83, 65],
       [74, 28, 92, 82],
       [30, 22, 17, 87]])

##### 10) Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [209]:
import pandas as pd

In [208]:
two_dim_arr=np.array([[2,4,6],[8,10,12],[14,18,20]])
two_dim_arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 18, 20]])

In [217]:
df=pd.DataFrame(two_dim_arr,columns=['A','B','C'])

In [218]:
df

A   B   C
0   2   4   6
1   8  10  12
2  14  18  20

### Section C: Exploring Pandas

##### 11) Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
##### - Use .info(), .describe()
##### - Select 'Name' and 'City' columns
##### - Drop 'City' column
##### - Fill any missing values in 'Salary' column with the mean
##### - Remove any duplicate rows


In [301]:
dict1={'Name':['Aswin','Athul','Abhishek','Aatlee','Abhidev','Gokul','Bharath','Sreerag','Karthik','Krishnan'],'Age':[21,20,23,27,28,25,16,29,18,19],
       'City':['Bengaluru','Madiwala','Lalbagh','HSR','Goa','Agara','Depot','Uduppi','Sarakki','Kengeri'],
       'Salary':[120000,50000,25000,15000,67000,40000,150000,30000,]}
dict1['Salary'].extend([np.nan, np.nan])

In [302]:
df1=pd.DataFrame(dict1)

In [303]:
df1

Name  Age       City    Salary
0     Aswin   21  Bengaluru  120000.0
1     Athul   20   Madiwala   50000.0
2  Abhishek   23    Lalbagh   25000.0
3    Aatlee   27        HSR   15000.0
4   Abhidev   28        Goa   67000.0
5     Gokul   25      Agara   40000.0
6   Bharath   16      Depot  150000.0
7   Sreerag   29     Uduppi   30000.0
8   Karthik   18    Sarakki       NaN
9  Krishnan   19    Kengeri       NaN

In [306]:
### info()
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [307]:
### describe()
df1.describe()

Age         Salary
count  10.000000       8.000000
mean   22.600000   62125.000000
std     4.501851   48348.253034
min    16.000000   15000.000000
25%    19.250000   28750.000000
50%    22.000000   45000.000000
75%    26.500000   80250.000000
max    29.000000  150000.000000

In [300]:
### Selecting 'Name' column
df1.Name

0       Aswin
1       Athul
2    Abhishek
3      Aatlee
4     Abhidev
5       Gokul
6     Bharath
7     Sreerag
8     Karthik
9    Krishnan
Name: Name, dtype: object

In [308]:
### Selecting 'City' column
df1.City

0    Bengaluru
1     Madiwala
2      Lalbagh
3          HSR
4          Goa
5        Agara
6        Depot
7       Uduppi
8      Sarakki
9      Kengeri
Name: City, dtype: object

In [309]:
### Dropping 'City' Column
df1.drop(columns=["City"],inplace=True)
df1

Name  Age    Salary
0     Aswin   21  120000.0
1     Athul   20   50000.0
2  Abhishek   23   25000.0
3    Aatlee   27   15000.0
4   Abhidev   28   67000.0
5     Gokul   25   40000.0
6   Bharath   16  150000.0
7   Sreerag   29   30000.0
8   Karthik   18       NaN
9  Krishnan   19       NaN

In [310]:
### Chcking missing values
df1.isnull().sum()

Name      0
Age       0
Salary    2
dtype: int64

In [311]:
df1.Salary.mean()

62125.0

In [312]:
df1.fillna({'Salary':df1.Salary.mean()},inplace=True)

In [297]:

df1.duplicated().sum()

0

In [298]:
df1.drop_duplicates(ignore_index=True,inplace=True)

In [299]:
df1

Name  Age    Salary
0     Aswin   21  120000.0
1     Athul   20   50000.0
2  Abhishek   23   25000.0
3    Aatlee   27   15000.0
4   Abhidev   28   67000.0
5     Gokul   25   40000.0
6   Bharath   16  150000.0
7   Sreerag   29   30000.0
8   Karthik   18   62125.0
9  Krishnan   19   62125.0